### ISSUE TITLE
Errors on first run

### ISSUE THREAD

**Issue by terrance-orletsky-d7** [jancurn/actor-find-broken-links#10]
I downloaded this repo, ran `npm i` and then `apify run` and I get:
```
The new version of Apify CLI uses a new format of the "apify.json" file. Your file will be automatically updated 
to the new format. Yes
```
I chose 'Yes' and then I get a fatal error:

```
Error: Cannot find module 'underscore'

Require stack:
- /Users/torletsky/Sites/domain7/actor-find-broken-links-master/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/torletsky/Sites/domain7/actor-find-broken-links-master/main.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/torletsky/Sites/domain7/actor-find-broken-links-master/main.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! actor-find-broken-links@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the actor-find-broken-links@1.0.0 start script.

```

How do I proceed, please?

**Comment by jancurn** [comment]
Please note that the tool is designed to run on Apify. Have you tried running it there? See https://apify.com/jancurn/find-broken-links
